---
- name: Deploy Raddit App
  hosts: raddit-app
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/Artemmkin/raddit.git'
        dest: /var/lib/raddit
      register: clone

- name: Install application dependencies
  become: true
  bundler:
    state: present
    chdir: /var/lib/raddit
  when: clone.changed
  notify: restart raddit

handlers:
  - name: restart raddit
    become: true
    systemd: name=raddit state=restarted